services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules  # Empêche Docker d'écraser node_modules
    environment:
      - VITE_API_URL=http://backend:8000
    command: ["npm", "run", "dev", "--", "--host"]
    networks:
      - plantcare-network

networks:
  plantcare-network:
    driver: bridge
